"""empty message

Revision ID: f1f4774d7c75
Revises: 0e74d2ac0037
Create Date: 2023-07-31 14:08:55.119474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f4774d7c75'
down_revision = '0e74d2ac0037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
